# Generated by Django 5.0.2 on 2026-01-08 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Docket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Ministry of ICT or Nairobi City County",
                        max_length=255,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("NATIONAL_EXECUTIVE", "National Executive (Ministries)"),
                            (
                                "NATIONAL_PARLIAMENT",
                                "Parliament (Senate/National Assembly)",
                            ),
                            ("COUNTY_EXECUTIVE", "County Executive"),
                            ("COUNTY_ASSEMBLY", "County Assembly"),
                            ("JUDICIARY", "Judiciary"),
                            (
                                "INDEPENDENT_COMMISSION",
                                "Independent Commission (IEBC, NEMA, etc.)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Legal definition/context for this category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. The Finance Bill 2026", max_length=300
                    ),
                ),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "participation_deadline",
                    models.DateField(
                        help_text="The cutoff date for public submissions"
                    ),
                ),
                (
                    "legal_text_url",
                    models.URLField(help_text="Link to the PDF of the Bill/Policy"),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="A simplified summary for the public"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft / Internal Review"),
                            ("GAZETTED", "Gazetted / Published"),
                            ("PUBLIC_PARTICIPATION", "Open for Public Views"),
                            ("COMMITTEE_STAGE", "Committee Review"),
                            ("PASSED", "Passed / Enacted"),
                            ("REJECTED", "Rejected / Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="legislative_tracker.instrumentcategory",
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="legislative_tracker.docket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("constituency", models.CharField(blank=True, max_length=150)),
                ("ward", models.CharField(blank=True, max_length=150)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SUPPORT", "Support"),
                            ("OPPOSE", "Oppose"),
                            ("AMEND", "Propose Amendments"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "image_evidence",
                    models.ImageField(
                        blank=True,
                        help_text="Upload photos (e.g. current state of road for CIDP)",
                        null=True,
                        upload_to="feedback_evidence/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="legislative_tracker.legalinstrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="status_reports/"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_reports",
                        to="legislative_tracker.legalinstrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
