# Generated by Django 5.0.2 on 2026-01-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legislative_tracker", "0001_initial"),
        ("locations", "0003_official"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicfeedback",
            name="constituency_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to="locations.constituency",
            ),
        ),
        migrations.AddField(
            model_name="publicfeedback",
            name="proposed_alternative",
            field=models.TextField(blank=True, help_text="Proposed alternative text"),
        ),
        migrations.AddField(
            model_name="publicfeedback",
            name="target_clause",
            field=models.CharField(
                blank=True, help_text="Which clause/section to amend", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="publicfeedback",
            name="ward_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to="locations.ward",
            ),
        ),
    ]
