services:
  - type: web
    name: constituent-feedback-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn feedback_platform.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: constituent-feedback-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: constituent-feedback-db
    databaseName: constituent_feedback
    user: constituent_feedback_user
