# Generated by Django 5.1.6 on 2025-03-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_media_file_url_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.RemoveField(
            model_name='media',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_type',
        ),
    ]
