# Generated by Django 5.1.7 on 2025-03-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_media_options_remove_media_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='feedback',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='feedback.feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default=1, upload_to='feedback_media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
