# Generated by Django 6.0.1 on 2026-01-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 047 for Nairobi", max_length=3, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituencies",
                        to="locations.county",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Constituencies",
                "ordering": ["name"],
                "unique_together": {("county", "name")},
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="locations.constituency",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("constituency", "name")},
            },
        ),
    ]
