# Generated by Django 5.0.2 on 2026-01-08 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="county",
            options={"ordering": ["name"], "verbose_name_plural": " Counties"},
        ),
    ]
