# Generated by Django 5.0.2 on 2026-01-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_county_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Official",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("MCA", "Member of County Assembly"),
                            ("MP", "Member of Parliament"),
                            ("GOV", "Governor"),
                            ("SEN", "Senator"),
                            ("WOMAN_REP", "Woman Representative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="officials/"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Public contact number", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Public email address", max_length=254
                    ),
                ),
                (
                    "whatsapp_link",
                    models.URLField(blank=True, help_text="Direct WhatsApp API link"),
                ),
                (
                    "constituency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officials",
                        to="locations.constituency",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officials",
                        to="locations.county",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officials",
                        to="locations.ward",
                    ),
                ),
            ],
        ),
    ]
