# Generated by Django 5.0.2 on 2026-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Legal & Regulatory"),
                            ("LEGISLATIVE", "Legislative"),
                            ("ELECTORAL", "Electoral"),
                            ("DATA", "Data & Statistics"),
                            ("SERVICES", "Government Services"),
                        ],
                        default="SERVICES",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("source_name", models.CharField(max_length=200)),
                ("url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
