# Generated by Django 5.0.2 on 2026-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="source_name",
            field=models.CharField(max_length=500),
        ),
    ]
